// 
// Decompiled by Procyon v0.5.36
// 

package DEOBFUSCATED-NAMES;

public class str
{
    public static final String bar;
    public static final String c11;
    public static final String c12;
    public static final String c13;
    public static final String c14;
    public static final String c15;
    public static final String c16;
    public static final String c17;
    public static final String c18;
    public static final String c20;
    public static final String c21;
    public static final String c22;
    public static final String c23;
    public static final String c24;
    public static final String c25;
    public static final String c26;
    public static final String c27;
    public static final String c28;
    public static final String c29;
    public static final String c30;
    public static final String c31;
    public static final String c32;
    public static final String c33;
    public static final String c34;
    public static final String c35;
    public static final String c36;
    public static final String c37;
    public static final String c38;
    public static final String c39;
    public static final String c40;
    public static final String c41;
    public static final String c42;
    public static final String c43;
    public static final String c44;
    public static final String c45;
    public static final String c46;
    public static final String c47;
    public static final String c48;
    public static final String c49;
    public static final String c50;
    public static final String c51;
    public static final String c52;
    public static final String c53;
    public static final String c54;
    public static final String c55;
    public static final String c56;
    public static final String c57;
    public static final String c58;
    public static final String c59;
    public static final String c60;
    public static final String c61;
    public static final String c62;
    public static final String c63;
    public static final String c64;
    public static final String c65;
    public static final String c66;
    public static final String c67;
    public static final String c68;
    public static final String c70;
    public static final String co1;
    public static final String co2;
    public static final String co3;
    public static final String co4;
    public static final String edit_hud_pos;
    public static final String f1;
    public static final String f2;
    public static final String f3;
    public static final String f4;
    public static final String f5;
    public static final String f6;
    public static final String f7;
    public static final String f8;
    public static final String f9;
    public static final String f10;
    
    static {
        bar = new String(new char[] { '&', '7', '&', 'm', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-' });
        c11 = new String(new char[] { 'k', 'e', 'y' });
        c12 = new String(new char[] { 'I', 'n', 'v', 'a', 'l', 'i', 'd' });
        c13 = new String(new char[] { 's', 'e', 't', 'k', 'e', 'y' });
        c14 = new String(new char[] { 'j', 'o', 'i', 'n', 'e', 'd' });
        c15 = new String(new char[] { '(', '2', '/', '2', ')', '!' });
        c16 = new String(new char[] { 'S', 'u', 'c', 'c', 'e', 's', 's' });
        c17 = new String(new char[] { 'S', 'e', 't', 't', 'i', 'n', 'g' });
        c18 = new String(new char[] { '.', '.', '.' });
        c20 = new String(new char[] { 'S', 'e', 'n', 'd' });
        c21 = new String(new char[] { 'A', 'P', 'I', ' ', 'K', 'e', 'y' });
        c22 = new String(new char[] { 'i', 's', ' ', 'e', 'm', 'p', 't', 'y' });
        c23 = new String(new char[] { 'U', 's', 'e', ' ', '\"', 's', 'e', 't', 'k', 'e', 'y', ' ', '[', 'a', 'p', 'i', '_', 'k', 'e', 'y', ']', '\"', '.' });
        c24 = new String(new char[] { 'T', 'h', 'e', 'r', 'e', ' ', 'w', 'a', 's', ' ', 'a', 'n', ' ', 'e', 'r', 'r', 'o', 'r', '.' });
        c25 = new String(new char[] { 'd', 'o', 'e', 's', ' ', 'n', 'o', 't', ' ', 'e', 'x', 'i', 's', 't', '!' });
        c26 = new String(new char[] { 'W', 'i', 'n', 's', ':' });
        c27 = new String(new char[] { 'L', 'o', 's', 's', 'e', 's', ':' });
        c28 = new String(new char[] { 'W', 'L', 'R', ':' });
        c29 = new String(new char[] { 'W', 'i', 'n', 's', 't', 'r', 'e', 'a', 'k', ':' });
        c30 = new String(new char[] { 'c', 'l', 'e', 'a', 'r' });
        c31 = new String(new char[] { 'R', 'e', 't', 'r', 'i', 'e', 'v', 'i', 'n', 'g', ' ', 'd', 'a', 't', 'a', '.', '.', '.' });
        c32 = new String(new char[] { 'a', 'p', 'i', ':' });
        c33 = new String(new char[] { 'M', 'a', 'p', ':' });
        c34 = new String(new char[] { 'P', 'l', 'a', 'y', 'e', 'r', 's', ':' });
        c35 = new String(new char[] { '/', '2' });
        c36 = new String(new char[] { 'h', 'a', 's' });
        c37 = new String(new char[] { 'i', 's', ' ', 'n', 'i', 'c', 'k', 'e', 'd', '!' });
        c38 = new String(new char[] { 'W', 'S', ':' });
        c39 = new String(new char[] { 'q', 'u', 'i', 't', '!' });
        c40 = new String(new char[] { 'W', 'e', 'l', 'c', 'o', 'm', 'e', ',' });
        c41 = new String(new char[] { 'U', 's', 'e', ' ', '\"', 'h', 'e', 'l', 'p', '\"', ' ', 'f', 'o', 'r', ' ', 'h', 'e', 'l', 'p', '.' });
        c42 = new String(new char[] { 'h', 'e', 'l', 'p' });
        c43 = new String(new char[] { 'A', 'v', 'a', 'i', 'l', 'a', 'b', 'l', 'e', ' ', 'c', 'o', 'm', 'm', 'a', 'n', 'd', 's', ':' });
        c44 = new String(new char[] { 'd', 'u', 'e', 'l', 's', ' ', '[', 'p', 'l', 'a', 'y', 'e', 'r', ']' });
        c45 = new String(new char[] { 's', 'e', 't', 'k', 'e', 'y', ' ', '[', 'k', 'e', 'y', ']' });
        c46 = new String(new char[] { '[', 'N', 'P', 'C', ']' });
        c47 = new String(new char[] { 'n', 'i', 'c', 'k' });
        c48 = new String(new char[] { 'N', 'i', 'c', 'k', ' ', 'h', 'a', 's', ' ', 'b', 'e', 'e', 'n', ' ', 's', 'e', 't', ' ', 't', 'o', ':' });
        c49 = new String(new char[] { 'n', 'a', 'm', 'e' });
        c50 = new String(new char[] { 'm', 'o', 'b', '.', 'e', 'n', 'd', 'e', 'r', 'm', 'e', 'n', '.', 'p', 'o', 'r', 't', 'a', 'l' });
        c51 = new String(new char[] { 'p', 'i', 'n', 'g' });
        c52 = new String(new char[] { 'U', 'n', 'k', 'n', 'o', 'w', 'n' });
        c53 = new String(new char[] { 'P', 'l', 'e', 'a', 's', 'e', ' ', 'w', 'a', 'i', 't', '.' });
        c54 = new String(new char[] { 'C', 'h', 'e', 'c', 'k', 'i', 'n', 'g' });
        c55 = new String(new char[] { 'Y', 'o', 'u', 'r' });
        c56 = new String(new char[] { 'm', 's' });
        c57 = new String(new char[] { 'T', 'h', 'r', 'e', 'a', 't' });
        c58 = new String(new char[] { 'V', 'E', 'R', 'Y' });
        c59 = new String(new char[] { 'H', 'I', 'G', 'H' });
        c60 = new String(new char[] { 'M', 'O', 'D', 'E', 'R', 'A', 'T', 'E' });
        c61 = new String(new char[] { 'L', 'O', 'W' });
        c62 = new String(new char[] { 'O', 'p', 'p', 'o', 'n', 'e', 'n', 't' });
        c63 = new String(new char[] { 'f', 'o', 'u', 'n', 'd' });
        c64 = new String(new char[] { 'D', 'e', 'b', 'u', 'g' });
        c65 = new String(new char[] { 'e', 'n', 'a', 'b', 'l', 'e', 'd' });
        c66 = new String(new char[] { 'd', 'i', 's', 'a', 'b', 'l', 'e', 'd' });
        c67 = new String(new char[] { 'c', 'o', 'm', 'm', 'a', 'n', 'd' });
        c68 = new String(new char[] { 'r', 'e', 'm', 'o', 'v', 'e' });
        c70 = new String(new char[] { 'm', 'o', 'd', 'e' });
        co1 = new String(new char[] { '&', 'a' });
        co2 = new String(new char[] { '&', 'c' });
        co3 = new String(new char[] { '&', '3' });
        co4 = new String(new char[] { '&', 'e' });
        edit_hud_pos = new String(new char[] { 'E', 'd', 'i', 't', ' ', 't', 'h', 'e', ' ', 'H', 'U', 'D', ' ', 'p', 'o', 's', 'i', 't', 'i', 'o', 'n', ' ', 'b', 'y', ' ', 'd', 'r', 'a', 'g', 'g', 'i', 'n', 'g', '.' });
        f1 = new String(new char[] { 'u', 'w', 'u' });
        f2 = new String(new char[] { 'n', 'y', 'a' });
        f3 = new String(new char[] { 'i', 'c', 'h', 'i', ' ', 'n', 'i', ' ', 's', 'a', 'n' });
        f4 = new String(new char[] { 'a', 'r', 'i', 'g', 'a', 't', 'o', 'u', '!' });
        f5 = new String(new char[] { 's', 'h', 'o', 'u', 't', 'o', 'u', 't' });
        f6 = new String(new char[] { 'C', 'e', 'l', 'e', 'b', 'r', 'i', 't', 'i', 'e', 's', ':' });
        f7 = new String(new char[] { '-', ' ', 'h', 'e', 'v', 'e', 'x' });
        f8 = new String(new char[] { '-', ' ', 'j', 'c' });
        f9 = new String(new char[] { '-', ' ', 'm', 'o', 'o', 'd' });
        f10 = new String(new char[] { '-', ' ', 'c', 'h', 'a', 'r', 'l', 'o', 't', 't', 'e' });
    }
}
